export const MENS_CATEGORIES_ACTION_TYPE = {
    FETCH_MENS_CATEGORIES_START: 'FETCH_MENS_CATEGORIES_START',
    FETCH_MENS_CATEGORIES_SUCCESS: 'FETCH_MENS_CATEGORIES_SUCCESS',
    FETCH_MENS_CATEGORIES_FAILED: 'FETCH_MENS_CATEGORIES_FAILED',
}


// export const MENS_CATEGORIES_ACTION_TYPE = {
//   SET_MENS_CATEGORIES_MAP: "mens/SET_CATEGORIES_MAP",
//   SET_MENS: "mens/SET_MENS",
// };