export const WOMENS_CATEGORIES_ACTION_TYPE = {
  FETCH_WOMENS_CATEGORIES_START: "FETCH_WOMENS_CATEGORIES_START",
  FETCH_WOMENS_CATEGORIES_SUCCESS: "FETCH_WOMENS_CATEGORIES_SUCCESS",
  FETCH_WOMENS_CATEGORIES_FAILED: "FETCH_WOMENS_CATEGORIES_FAILED",
};

